version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectos_tecnicos
      MYSQL_USER: osvaldo
      MYSQL_PASSWORD: osvaldo123
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d 

